version = 1

test_patterns = [
    "src/**",
    "dist/**",
    "test/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  style_guide = "airbnb"
  dialect = "typescript"
