blank_issues_enabled: false
contact_links:
  - name: ❗️ All other issues
    url: mailto:hi@reinaldyrafli.com
    about: |
      Please contact the developer directly for other issues and asking questions.
