name: Code Coverage

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  codecov:
    name: Code Coverage
    runs-on: ubuntu-latest
    container: node:14.17.0
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: winston
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      mysql:
        image: mysql:8.0.25
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: winston
        ports:
          - 3306:3306
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installling dependencies
        run: yarn

      - name: Lint check
        run: yarn lint

      - name: Building code
        run: yarn build

      - name: Postgres Test
        run: yarn test
        env:
          MYSQL_CONNECTION_URL: mysql://root:password@mysql:3306/winston
          POSTGRES_CONNECTION_URL: postgresql://postgres:password@postgres:5432/winston
      
      - name: Upload to Codecov
        run: bash <(curl -s https://codecov.io/bash)