name: Environment Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  environment-test:
    name: Environment Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup nodejs
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ">=14"
      - name: Installling dependencies
        run: npm install
      - name: Lint check
        run: npm run lint
      - name: Building code
        run: npm run build
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1