name: "Test"
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    - name: Test
    - runs-on: ubuntu-latest
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'winston_knex'
        mysql root password: 'password'
    - name: Setup PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '13'
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.4
      with:
        node-version: ">=14"
    - name: Installing dependencies
      run: |
        npm install
        npm audit
    - name: Running test
      run: npm run coverage
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1
      with:
        directory: coverage
        file: coverage-final.json

      